class OW_Map:
    dorado = 'http://www.owfire.com/images/maps/dorado-3.jpg'
    eichenwalde = 'http://media1.gameinformer.com/imagefeed/screenshots/Overwatch/OW_Eichenwalde_17.jpg'
    rio = 'http://images.pushsquare.com/news/2016/08/hands_on_overwatchs_olympian_ps4_update_scores_with_rocket_league_mode/attachment/2/original.jpg'
    hanamura = 'http://www.owfire.com/images/maps/hanamura-1.jpg'
    hollywood = 'http://i0.wp.com/www.geeksandcom.com/wp-content/uploads/2015/11/Overwatch-Hollywood.jpg'
    ilios = 'http://tse3.mm.bing.net/th?id=OIP._w8hoVAgibFCc5vabEgJJQEsCo&pid=15.1'
    kings_row = 'http://www.helderpinto.com/wp-content/uploads/2014/11/Helder_Pinto_Kings_Row_02.jpg'
    lijiang_tower = 'http://vignette2.wikia.nocookie.net/overwatch/images/e/ed/Lijiang_screenshot_34.jpg/revision/latest/scale-to-width-down/2000?cb=20160711182404'
    route_66 = 'http://www.offgamers.com/blog/wp-content/uploads/2016/03/dtftgbyvrmcxqwrnid76.jpg'
    numbani = 'http://www.owfire.com/images/maps/numbani-4.jpg'
    nepal = 'http://www.gameinformer.com/resized-image.ashx/__size/610x0/__key/CommunityServer-Components-SiteFiles/imagefeed-featured-blizzard-overwatch-gamer_2D00_culture/nepal_5F00_overwatch_5F00_610.jpg'
    temple_of_anubis = 'http://cdn.mos.cms.futurecdn.net/QmgmSXRZ4SmoWA7yi7ekWm-650-80.jpg'
    volskaya_industries = 'https://4.bp.blogspot.com/-U2msLyRa6uo/V0QZlLDn7MI/AAAAAAAAAkA/_9mROobNtG4eycJrtfEREhFaud0EwkS6QCLcB/s1600/Volskaya_011.jpg'
    watchpoint_gibraltar = 'http://wiki.teamliquid.net/commons/images/thumb/8/8b/Gibraltar.jpg/600px-Gibraltar.jpg'
    ecopoint_antarctica = 'http://2static.fjcdn.com/pictures/New+overwatch+map+ecopoint+antarctica_85f8d3_6077872.jpg'
